### ISSUE TITLE
Probleme with the touchscreen

### ISSUE THREAD

**Issue by spectrenoir06** [InfiniteYuan1/esp32-lvgl-gui#1]
Hello,
I use a ili9341 + xpt2046
I use the ili9341 on 4-line serial interface II mode ( miso + mosi + sck + dc + cs )
and the xpt2046 on spi with only ( miso + mosi + cs )

The LCD work great ( I just need to select a invalid gpio ( 0 ) in menuconfig for the reset and de backlight gpio )
but the tactile doesn't work.
I think it's because the driver of the xpt2046 need to use the IRQ gpio but on my project I don't use it ( it work fine with other driver and other GUI lib.

**Comment by InfiniteYuan** [comment]
You can use the driver I provided.Can you look at the log for running?

**Comment by InfiniteYuan** [comment]
Can you look at your io configuration?

**Comment by spectrenoir06** [comment]
I try the driver you provide, it dont work because on my project i don't have a gpio of the esp32 connect to the irq of the XPT2046
but It work with other gui with other driver. ( like GUIslice with eSPI )

**Comment by InfiniteYuan** [comment]
you should connect IRQ pin for  xpt2046 work use my driver.or, you rewrite xpt2046 driver for lvgl
