### ISSUE TITLE
Try to compile the example

### ISSUE THREAD

**Issue by spectrenoir06** [InfiniteYuan1/esp32-lvgl-gui#3]
Hello I try t build the demo of lvgl but i have this error

CXX build/gdrivers/gdisp/ILI9341/ILI9341_adapter.o
In file included from /home/spectre/dev/git/esp32-lvgl gui/components/gdrivers/include/lvgl_disp_config.h:5:0,
                 from /home/spectre/dev/git/esp32-lvgl-gui/components/gdrivers/gdisp/ILI9341/ILI9341_adapter.cpp:211:
/home/spectre/dev/git/esp32-lvgl-gui/components/lvgl_gui/include/iot_lvgl.h:14:18: fatal error: lvgl.h: No such file or directory
compilation terminated.

**Comment by InfiniteYuan** [comment]
Oh, you should use `git submodule update --init --recursive` to fetch lvgl reposity
