### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by linyaqiang** [InfiniteYuan1/esp32-lvgl-gui#4]
为什么我git下来你这代码，然后把path设置好了，编译的时候出现如下错误：
AR build/ili9806/libili9806.a
CXX build/infrared/ir_nec.o
AR build/infrared/libinfrared.a
CC build/iot_espnow/iot_espnow.o
AR build/iot_espnow/libiot_espnow.a
CC build/is31fl3xxx/is31fl3736.o
CC build/is31fl3xxx/is31fl3218.o
CXX build/is31fl3xxx/is31fl3218_obj.o
CXX build/is31fl3xxx/is31fl3736_obj.o
AR build/is31fl3xxx/libis31fl3xxx.a
CC build/jsmn/src//jsmn.o
AR build/jsmn/libjsmn.a
CC build/json/cJSON/cJSON.o
CC build/json/cJSON/cJSON_Utils.o
AR build/json/libjson.a
CC build/lcd/glcdfont.o
CC build/lcd/spi_lcd.o
CC build/lcd/font7s.o
CC build/lcd/Adafruit-GFX-Library/glcdfont.o
D:/lin_work/esp32_work/esp32_prj/esp/esp-iot-solution/components/spi_devices/lcd/Adafruit-GFX-Library/glcdfont.c:18:28: error: 'font' defined but not used [-Werror=unused-const-variable=]
 static const unsigned char font[] PROGMEM = {
                            ^~~~
cc1.exe: some warnings being treated as errors
make[1]: *** [/d/lin_work/esp32_work/esp32_prj/esp/esp-idf/make/component_wrapper.mk:292：Adafruit-GFX-Library/glcdfont.o] 错误 1
make: *** [D:/lin_work/esp32_work/esp32_prj/esp/esp-idf/make/project.mk:584：component-lcd-build] 错误 2
能否帮我看下，万分感谢！

**Comment by InfiniteYuan** [comment]
加 Q:46052848

**Comment by linyaqiang** [comment]
我添加你的Q时，显示对方已拒绝了




------------------ 原始邮件 ------------------
发件人: "InfiniteYuan"<notifications@github.com>; 
发送时间: 2019年8月19日(星期一) 下午5:12
收件人: "InfiniteYuan1/esp32-lvgl-gui"<esp32-lvgl-gui@noreply.github.com>; 
抄送: ".L.A.Q．"<1185760301@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [InfiniteYuan1/esp32-lvgl-gui] 编译报错 (#4)




加 Q:46052848

**Comment by linyaqiang** [comment]
能否加下我的Q：1185760301




------------------ 原始邮件 ------------------
发件人: "InfiniteYuan"<notifications@github.com>; 
发送时间: 2019年8月19日(星期一) 下午5:12
收件人: "InfiniteYuan1/esp32-lvgl-gui"<esp32-lvgl-gui@noreply.github.com>; 
抄送: ".L.A.Q．"<1185760301@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [InfiniteYuan1/esp32-lvgl-gui] 编译报错 (#4)




加 Q:46052848
